- hosts: server
  become: true
  tasks:
    - name: Add the user app
      user:
        name: app
        uid: 1077
        shell: /bin/bash
        createhome: yes
        home: /home/app
    - name: Add group app to user admin
      user:
        name: admin
        groups: app
        append: yes
    - name: Add config for acceptance
      template:
        src: templates/config.acceptance.yml
        dest: /opt/config.acc.yml
        owner: app
        group: app
        mode: "0600"
    - name: Add config for production
      template:
        src: templates/config.production.yml
        dest: /opt/config.prod.yml
        owner: app
        group: app
        mode: "0600"
    - name: Add app production service
      vars:
        app_service_name: "App Production"
        app_service_user: app
        app_service_env: production
        app_service_path: /opt/app-production
      template:
        src: templates/app.service.j2
        dest: /etc/systemd/system/app-production.service
        owner: root
        group: root
        mode: "0644"
    - name: Add app acceptance service
      vars:
        app_service_name: "App Acceptance"
        app_service_user: app
        app_service_env: acceptance
        app_service_path: /opt/app-acceptance
      template:
        src: templates/app.service.j2
        dest: /etc/systemd/system/app-acceptance.service
        owner: root
        group: root
        mode: "0644"
    - name: Systemd reload
      shell: |
        sudo systemctl daemon-reload
    # - name: Enable service app production
    #   service:
    #     name: app-production
    #     enabled: yes
    # - name: Enable service app acceptance
    #   service:
    #     name: app-acceptance
    #     enabled: yes
