- hosts: server
  become: true
  tasks:
    - name: Check what is installed
      package_facts:
        manager: "auto"
    - name: Install caddy
      ansible.builtin.shell: |
        apt install -y debian-keyring debian-archive-keyring apt-transport-https
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
        apt update
        apt install caddy -y
      when: "ansible_facts.packages['caddy'] is undefined"
    - name: Add caddy file
      ansible.builtin.template:
        src: templates/Caddyfile
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: "0644"
    - name: Replace PRERENDER_TOKEN
      replace:
        path: /etc/caddy/Caddyfile
        regexp: "PRERENDER_TOKEN"
        replace: "{{ prerender_token }}"
        owner: root
        group: root
        mode: "0644"
    - name: Replace MAILPIT_PASSWORD
      replace:
        path: /etc/caddy/Caddyfile
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
        owner: root
        group: root
        mode: "0644"
      with_items:
        - regexp: "TUFJTFBJVF9QQVNTV09SRA=="
          replace: "{{ mailpit_ui_password_bcrypt }}"
        - regexp: "TUFJTFBJVF9QQVNTV09SRF9HVUVTVF8x"
          replace: "{{ mailpit_ui_password_bcrypt_guest1 }}"
    - name: Add maintenance caddy file
      ansible.builtin.template:
        src: templates/Caddyfile.maint
        dest: /etc/caddy/Caddyfile.maint
        owner: root
        group: root
        mode: "0644"
    - name: Create caddy server files
      file:
        path: "{{ item }}"
        recurse: true
        state: directory
        mode: "0775"
        group: "caddy"
        owner: "caddy"
      with_items:
        - "/var/caddy/acc.clothingloop.org"
        - "/var/caddy/app.clothingloop.org"
        - "/var/caddy/clothingloop.org"
        - "/var/caddy/maint.clothingloop.org"
        - "/var/caddy/images.clothingloop.org"
        - "/var/caddy/acc.app.clothingloop.org"
    - name: Copy maint files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: caddy
        group: caddy
        mode: "0775"
      with_items:
        - src: templates/maint/index.html
          dest: /var/caddy/maint.clothingloop.org/index.html
    - name: Setup caddy service
      ansible.builtin.service:
        name: caddy
        enabled: true
        state: reloaded
