- hosts: server
  become: true
  tasks:
    - name: Check what is installed
      package_facts:
        manager: "auto"
    - name: Add sury repository for php8.1
      shell: |
        apt-get update
        apt-get -y install apt-transport-https lsb-release ca-certificates curl
        curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg
        sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
        apt-get update
      when: "ansible_facts.packages['php8.1-fpm'] is undefined"
    - name: Install php
      apt:
        install_recommends: no
        pkg:
          - php8.1-fpm
          - php8.1-mbstring
          - php8.1-bcmath
          - php8.1-xml
          - php8.1-mysql
          - php8.1-common
          - php8.1-gd
          - php8.1-cli
          - php8.1-curl
          - php8.1-zip
          - php8.1-gd
    - name: Setup php service
      service:
        name: php8.1-fpm
        enabled: yes
        state: started
    - name: Install caddy
      shell: |
        apt install -y debian-keyring debian-archive-keyring apt-transport-https
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
        apt update
        apt install caddy -y
      when: "ansible_facts.packages['caddy'] is undefined"
    - name: Add caddy file
      template:
        src: templates/Caddyfile
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: "0644"
    - name: Disable caddy-api service
      service:
        name: caddy-api
        enabled: no
        state: stopped
    - name: Create caddy server files
      file:
        path: "{{ item }}"
        recurse: yes
        state: directory
        mode: "0775"
        group: "caddy"
        owner: "caddy"
      with_items:
        - "/var/caddy/acc.clothingloop.org"
        - "/var/caddy/phpmyadmin"
        # - "/var/caddy/clothingloop.org"
    - name: Setup caddy service
      service:
        name: caddy
        enabled: yes
        state: reloaded
