- hosts: server
  become: true
  tasks:
    - name: Add the user clothingloop
      user:
        name: clothingloop
        uid: 1077
        shell: /bin/bash
        createhome: yes
        home: /home/clothingloop
    - name: Add user opt directory
      file:
        path: "/home/clothingloop/opt"
        recurse: no
        state: directory
        mode: "0775"
        group: "clothingloop"
        owner: "clothingloop"
    - name: Add config for acceptance
      template:
        src: templates/config.acceptance.yml
        dest: /home/clothingloop/opt/config.acc.yml
        owner: clothingloop
        group: clothingloop
        mode: "0600"
    - name: Add config for production
      template:
        src: templates/config.production.yml
        dest: /home/clothingloop/opt/config.prod.yml
        owner: clothingloop
        group: clothingloop
        mode: "0600"
    - name: Add API production service
      vars:
        api_service_name: "Clothingloop API Production"
        api_service_user: clothingloop
        api_service_env: production
        api_service_exec: /home/clothingloop/opt/api-production
        api_service_path: /home/clothingloop/opt
      template:
        src: templates/api.service.j2
        dest: /etc/systemd/system/cl-api-production.service
        owner: root
        group: root
        mode: "0644"
    - name: Add API acceptance service
      vars:
        api_service_name: "Clothingloop API Acceptance"
        api_service_user: clothingloop
        api_service_env: acceptance
        api_service_exec: /home/clothingloop/opt/api-acceptance
        api_service_path: /home/clothingloop/opt
      template:
        src: templates/api.service.j2
        dest: /etc/systemd/system/cl-api-acceptance.service
        owner: root
        group: root
        mode: "0644"
    - name: Systemd reload
      shell: |
        systemctl daemon-reload
    - name: Enable service api production
      service:
        name: cl-api-production
        enabled: yes
    - name: Enable service api acceptance
      service:
        name: cl-api-acceptance
        enabled: yes
