project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /frontend/public/locales/en/*.json
    translation: /frontend/public/locales/%two_letters_code%/%original_file_name%
  - source: /server/internal/views/emails/en/*.*
    translation: /server/internal/views/emails/%two_letters_code%/%original_file_name%
    ignore:
      - "/server/internal/views/emails/en/contact_received.gohtml"
  - source: /public/locales/en/*.json
    translation: /public/locales/%two_letters_code%/%original_file_name%
