project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /frontend/public/locales/en/*.json
    translation: /frontend/public/locales/%two_letters_code%/%original_file_name%
