name: cl-dev

services:
  app:
    image: node:20-alpine
    # ports:
      # - 127.0.0.1:8081:8081
    #   - 5173:5173
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c 'npm i && npm run dev:docker'
  frontend:
    image: node:20-alpine
    # ports:
    #   - 3000:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c 'npm i; npm run start:lan'
  server:
    image: golang:1.22.3-alpine
    depends_on:
      - db
      - mailpit
      - nakama
    # ports:
    #   - 8084:8084
    volumes:
      - ./server:/app
    environment:
      - ENV=development
    working_dir: /app
    command: "go run cmd/server/main.go -c config.dev.yml"
  mailpit:
    image: axllent/mailpit
    ports:
      - 127.0.0.1:8025:8025
      - 127.0.0.1:8125:1025
    environment:
      - "MP_SMTP_AUTH_ACCEPT_ANY=true"
      - "MP_SMTP_AUTH_ALLOW_INSECURE=true"
      - "MP_WEBROOT=/mailpit/"
  pma:
    image: phpmyadmin:apache
    ports:
      - 127.0.0.1:8082:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=fb4aeaa6d860dbabe785675e
  db:
    image: mariadb
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=fb4aeaa6d860dbabe785675e
      - MYSQL_DATABASE=clothingloop
      - MYSQL_USER=clothingloop
      - MYSQL_PASSWORD=72bd3937e91363a747f810e7
    volumes:
      - mysql:/var/lib/mysql
      - ../../server/sql:/scripts
  nakama:
    platform: linux/amd64
    image: registry.heroiclabs.com/heroiclabs/nakama:3.22.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address postgres:localdb@nakama_postgres:5432/nakama &&
          exec /nakama/nakama --name nakama1 --database.address postgres:localdb@nakama_postgres:5432/nakama --logger.level DEBUG --session.token_expiry_sec 7200          
    restart: always
    links:
      - nakama_postgres:db
    depends_on:
      nakama_postgres:
        condition: service_healthy
    volumes:
      - nakama_data:/nakama/data
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
  nakama_postgres:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - nakama_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nakama"]
      interval: 3s
      timeout: 3s
      retries: 5
  caddy:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    depends_on:
      - app
      - frontend
      - server
      - mailpit
    ports:
      # website
      - 127.0.0.1:8080:80
      - 127.0.0.1:8081:81
      - 127.0.0.1:8065:85
volumes:
  mysql:
  nakama_data:
  nakama_db:
