services:
  app:
    build:
      context: ./app/
      args:
        - ENV=production
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: ./frontend/
      args:
        - ENV=production
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
  server:
    build: ./server/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/ping || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 1m
    environment:
      - ENV=production
      - HOST=0.0.0.0
      - PORT=80
      - SITE_BASE_URL_API=https://www.clothingloop.org/api
      - SITE_BASE_URL_FE=https://www.clothingloop.org
      - COOKIE_DOMAIN=clothingloop.org
      - COOKIE_HTTPS_ONLY=true
      - JWT_SECRET=$JWT_SECRET
      - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
      - STRIPE_WEBHOOK=$STRIPE_WEBHOOK
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - SMTP_HOST=$SMTP_HOST
      - SMTP_PORT=$SMTP_PORT
      - SMTP_SENDER=$SMTP_SENDER
      - SMTP_USER=$SMTP_USER
      - SMTP_PASS=$SMTP_PASS
      - GOSCOPE2_USER=$GOSCOPE2_USER
      - GOSCOPE2_PASS=$GOSCOPE2_PASS
      - SENDINBLUE_API_KEY=$SENDINBLUE_API_KEY
      - IMGBB_KEY=$IMGBB_KEY
      - ONESIGNAL_APP_ID=$ONESIGNAL_APP_ID
      - ONESIGNAL_REST_API_KEY=$ONESIGNAL_REST_API_KEY
      - APPSTORE_REVIEWER_EMAIL=$APPSTORE_REVIEWER_EMAIL
