services:
  acc_nakama:
    platform: linux/amd64
    image: registry.heroiclabs.com/heroiclabs/nakama:3.22.0
    # NAKAMA_DB=postgres:localdb@nakama_postgres:5432/nakama
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address $NAKAMA_DB &&
          exec /nakama/nakama --name nakama1 --database.address $NAKAMA_DB --logger.level DEBUG --config /nakama/data/config.yml
    restart: always
    volumes:
      - nakama_data:/nakama/data
    # ports:
    #   - "7349:7349"
    #   - "7350:7350"
    #   - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

