name: cl-dev

services:
  app:
    image: node:20-alpine
    ports:
      - 5173:5173
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c 'npm i && npm run dev:docker'
  frontend:
    image: node:20-alpine
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c 'npm i; npm run start:lan'
  server:
    image: golang:1.22-alpine
    depends_on:
      - db
      - mailpit
    ports:
      - 8084:8084
    volumes:
      - ./server:/app
    working_dir: /app
    command: "go run cmd/server/main.go -c config.dev.yml"
  mailpit:
    image: axllent/mailpit
    # ports:
    #   - 127.0.0.1:8025:8025
    #   - 127.0.0.1:8125:1025
    environment:
      - "MP_SMTP_AUTH_ACCEPT_ANY=true"
      - "MP_SMTP_AUTH_ALLOW_INSECURE=true"
      - "MP_WEBROOT=/mailpit/"
  pma:
    image: phpmyadmin:apache
    ports:
      - 127.0.0.1:8085:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=fb4aeaa6d860dbabe785675e
  db:
    image: mariadb
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=fb4aeaa6d860dbabe785675e
      - MYSQL_DATABASE=clothingloop
      - MYSQL_USER=clothingloop
      - MYSQL_PASSWORD=72bd3937e91363a747f810e7
    volumes:
      - mysql:/var/lib/mysql
      - ./server/sql:/scripts
  caddy:
    build:
      context: ./caddy/
    ports:
      - 127.0.0.1:8086:80
volumes:
  mysql:
