host: "0.0.0.0"
port: 80

jwt_secret: "826fa56956bb0bb546728c74"
cookie_domain: "localhost"
cookie_https_only: false

mailchimp_key: "invalid"

db_host: "localhost"
db_port: 3066
db_name: "clothingloop"
db_user: "clothingloop"
db_pass: "password"
