host: "127.0.0.1"
port: 8085

site_base_url: "http://localhost:8084"

cookie_domain: "localhost"
cookie_https_only: false

# see docker-compose cl_db
db_host: "localhost"
db_port: 3306
db_name: "clothingloop"
db_user: "clothingloop"
db_pass: "72bd3937e91363a747f810e7"

# see docker-compose cl_mail
smtp_host: "localhost"
smtp_port: 1025
smtp_sender: "test@gmail.com"
smtp_user: "test@gmail.com"
smtp_pass: "password123"
