production: true

host: "0.0.0.0"
port: 80

site_base_url: "https://clothingloop.org"

jwt_secret: "826fa56956bb0bb546728c74"
cookie_domain: "localhost"
cookie_https_only: false

db_host: "localhost"
db_port: 3066
db_name: "clothingloop"
db_user: "clothingloop"
db_pass: "password"

smtp_host: "smtp.gmail.com"
smtp_port: 587
smtp_sender: "test@gmail.com"
smtp_user: "test@gmail.com"
smtp_pass: "password123"