version: "3"

services:
  caddy:
    restart: always
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "433:443"
    depends_on:
      - app-production
      - app-acceptance
    volumes:
      - /data/caddy/etc:/etc/caddy:ro
      - /data/caddy/static:/static
      - /data/caddy/data:/data
      - /var/log/caddy/:/host-log/
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
  app-production:
    restart: always
    image: golang:latest
    depends_on:
      - mariadb
    volumes:
      - /data/app-production:/app
    command: sh -c 'cd /app/server; git fetch origin main; git checkout -f origin/main; go build -o /bin/app-production cmd/server; sh /bin/app-production'
  app-acceptance:
    restart: always
    image: golang:latest
    depends_on:
      - mariadb
    volumes:
      - /data/app-acceptance:/app
    command: sh -c 'cd /app/server; git fetch origin main; git checkout -f origin/main; go build -o /bin/app-acceptance cmd/server; sh /bin/app-acceptance'
  mariadb:
    restart: always
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - /data/mariadb:/var/lib/mysql