name: Deploy Acceptance v2
on:
  workflow_dispatch:
  push:
    branches:
      - golang

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Build binary
        run: make build-server
        working-directory: ./server
      - name: Rename binary
        run: mv server cl-api-acceptance
        working-directory: ./server
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS1_PRIVKEY }}
          known_hosts: ${{ secrets.VPS1_KNOWNHOSTS }}
      - name: Send binary to vps and restart service
        run: |
          rsync -az --delete ./server/cl-api-acceptance /home/admin/
          ssh admin@vpsnode1.vps.webdock.cloud /bin/bash -c "\
          sudo chown root:root /home/admin/cl-api-acceptance; \
          sudo chmod 0775 /home/admin/cl-api-acceptance; \
          sudo mv /home/admin/cl-api-acceptance /home/clothingloop/opt/api-acceptance; \
          sudo systemctl restart cl-api-acceptance"
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies Frontend
        run: npm ci
        working-directory: ./frontend
      - name: Build public files
        run: npm run build:acceptance
        working-directory: ./frontend
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS1_PRIVKEY }}
          known_hosts: ${{ secrets.VPS1_KNOWNHOSTS }}
      - name: Send public files to vps
        run: |
          ssh admin@vpsnode1.vps.webdock.cloud /bin/bash -c "mkdir -p /home/admin/cl-fe-acceptance"
          rsync -az --delete ./frontend/build/ admin@vpsnode1.vps.webdock.cloud/home/admin/cl-fe-acceptance/
          ssh admin@vpsnode1.vps.webdock.cloud /bin/bash -c "\
          sudo chown -R caddy:caddy /home/admin/cl-fe-acceptance; \
          sudo chmod -R 0775 /home/admin/cl-fe-acceptance; \
          sudo rm -rf /var/caddy/acc.clothingloop.org/{.*,*} || :; \
          sudo mv -f /home/admin/cl-fe-acceptance/{.*,*} /var/caddy/acc.clothingloop.org || :; \
          sudo systemctl reload caddy"
