name: Deploy Acceptance App
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - app/**

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json
      - name: Install Dependencies app
        run: npm ci
        working-directory: ./app
      - name: Build public files
        run: npm run build:acceptance
        working-directory: ./app
      - name: Install SSH key
        uses: benoitchantre/setup-ssh-authentication-action@1.0.1
        with:
          private-key: ${{ secrets.VPS2_PRIVKEY }}
          private-key-name: id_ed25519
          known-hosts: ${{ secrets.VPS2_KNOWNHOSTS }}
      - name: Send public files to vps
        run: |
          rsync -az --delete ./app/build/ admin@vps2.vps.webdock.cloud:/home/admin/acc.app.clothingloop.org/
          ssh admin@vps2.vps.webdock.cloud "sudo rsync -z -rlt --chown=www-data:www-data --chmod=0775 --delete /home/admin/acc.app.clothingloop.org/ /var/www/acc.app.clothingloop.org/"
          echo "done"
