name: Lint App
on:
  workflow_dispatch:
  push:
    paths:
      - app/**
      - "!app/public/locales/**"
  pull_request:
    paths:
      - app/**
      - "!app/public/locales/**"

jobs:
  lint-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5
          cache: npm
          cache-dependency-path: app/package-lock.json
      - name: Install Dependencies App
        run: npm ci
        working-directory: ./app
      - name: Run TypeScript test
        run: npx tsc
        working-directory: ./app
      - name: Run Prettier
        run: npm run lint:test
        working-directory: ./app
