name: Lint Frontend
on:
  workflow_dispatch:
  push:
    paths:
      - frontend/**
      - "!frontend/public/locales/**"
  pull_request:
    paths:
      - frontend/**
      - "!frontend/public/locales/**"

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install Dependencies Frontend
        run: npm ci
        working-directory: ./frontend
      - name: Run TypeScript test
        run: npx tsc
        working-directory: ./frontend
      - name: Run Prettier
        run: npm run lint:test
        working-directory: ./frontend
